### ISSUE TITLE
Bugtracker (required by QGIS)

### ISSUE THREAD

**Issue by MoritzMennenga** [t-systems-on-site-services-gmbh/geoCore#1]
Issue to fulfill the requirement by QGIS to have one open issue in the bugtracker.

**Comment by PhilipMay** [comment]
Hey @MoritzMennenga - whats up? Can we help with this software?

**Comment by MoritzMennenga** [comment]
If the values in front of the brackets in the petro column is missing, Qgis crashes. 
Maybe handling the error or set a null-value width = 0.01 would be an idea
