### ISSUE TITLE
Please allow public comments on the bugtracker

### ISSUE THREAD

**Issue by pcav** [t-systems-on-site-services-gmbh/geoCore#40]
Currently I cannot leave comments, nor close resolved tickets.
Thanks.

**Comment by PhilipMay** [comment]
@gricklom is there anything I should change / configure?
I think you are also allowed to do that.

**Comment by MoritzMennenga** [comment]
additional Information: open bugtracker is necessary for an upload in the QGIS-Extension library - [geoCore](https://plugins.qgis.org/plugins/geoCore/)

**Comment by pcav** [comment]
Apparently only #1 is closed.

**Comment by gricklom** [comment]
@pcav: You're right, only issue #1 is locked. This is because it was reused to report another bug. This creates havoc. Everyone is free to create issues and to comment on them.
By the way, is it really necessary to have an open bug in our bug-tracker for QGis? Isn't it enough to mention the url of our bug-tracker in the metadata.txt?

**Comment by pcav** [comment]
An open bug tracker is a requirement.

Il 11 marzo 2021 19:40:01 CET, Gerrit Bette ***@***.***> ha scritto:
***@***.***: You're right, only issue #1 is locked. This is because it was
>reused to report another bug. This creates havoc. Everyone is free to
>create issues and to comment on them.
>By the way, is it really necessary to have an open bug in our
>bug-tracker for QGis? Isn't it enough to mention the url of our
>bug-tracker in the metadata.txt?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/t-systems-on-site-services-gmbh/geoCore/issues/40#issuecomment-796956091

-- 
Sorry for being short

**Comment by PhilipMay** [comment]
I think here might be a confusion between:
- open bug tracker
- open bug

This GitHub repository definitely has an open bug **tracker**.

**Comment by gricklom** [comment]
Hello @pcav, I think Philip is right. Is there maybe a confusion between an open bug and an open bug (or issue) tracker? We have the latter in place. Would it be ok to just provide the link https://github.com/t-systems-on-site-services-gmbh/geoCore/issues/ in the metadata.txt?

**Comment by pcav** [comment]
agreed, thanks

**Comment by gricklom** [comment]
Thanks!

**Comment by gricklom** [comment]
Resolved in commit 3ad2504
