### ISSUE TITLE
Python error trying to use the plugin

### ISSUE THREAD

**Issue by VincentD** [t-systems-on-site-services-gmbh/geoCore#47]
Hello,

Trying to use geocore, it induces a Python error.
We've tried to use the plugin on 2 pc, on Windows and Linux (QGIS 3.22 on both).

Do you see what can happen?

Please find below the log, and in attachments the shapefile and text file we used : 

```
KeyError: 'zcoorddb' 
Traceback (most recent call last):
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 157, in showEvent
    self.drawProfilesNorthSouth()
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 277, in drawProfilesNorthSouth
    self._drawProfiles(crit)
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 303, in _drawProfiles
    pac = builder.getProfilesAndConnectors(features)
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profileBuilder.py", line 96, in getProfilesAndConnectors
    yp = f.attribute(self.config.settings["zCoord"]) * 100 # convert to cm
KeyError: 'zcoorddb'


Version de Python : 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
Version de QGIS : 3.22.6-Białowieża Białowieża, b6f33b1a9f 

Chemin Python :
/usr/share/qgis/python
/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python
/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/vincent/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python
/media/u_ppige09lambert93/LIDAR/Scarpe/20190228_RGEALTI_MNT_1M_ASC_LAMB93_IGN69_DGPR-17LI065-AUTHIE-BOULONNAIS/2022_ScarpeAmont_SIG_LIDAR
```

Thanks in advance,
Greetings

[a_renommer_comme_il_faut.csv](https://github.com/t-systems-on-site-services-gmbh/geoCore/files/8700312/a_renommer_comme_il_faut.csv)
[extraction_raster.zip](https://github.com/t-systems-on-site-services-gmbh/geoCore/files/8700321/extraction_raster.zip)

**Comment by PhilipMay** [comment]
@gricklom do you see the error?

**Comment by MoritzMennenga** [comment]
Hello, the error should come from the fact that the config.yml is not adapted to the data. If you navigate to the plugin folder (In Qgis Settings - User profiles - open active plugin folder -> then python - geoCore - config) open the config.yml and insert the adapted code it should work. I have tried it successfully with your data for me.
You can find a video tutorial on youtube: [https://www.youtube.com/watch?v=kMyllvit1UI](url)
One level below is the geoCore.yml, which must be adapted to the data for the layout (see video).


```
# columns in borehole data
boreholeId: ID
xCoord: xcoord
yCoord: ycoord
zCoord: zcoord

# columns in layer data
dataId: ID
layerNo: layerno
group: group
depthFrom: depth_from
depthTo: depth_to
petrography: petrography
color: colour
facies: facies
comment: comment
```

**Comment by PhilipMay** [comment]
Thanks for this answer @MoritzMennenga .

@VincentD does this solve your issue?

**Comment by VincentD** [comment]
> Thanks for this answer @MoritzMennenga .
> 
> @VincentD does this solve your issue?

Thank you very much @PhilipMay and @MoritzMennenga, this problem is solved : it was just a problem with the name of the Zcoord field.
Greetings
