### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by VincentD** [t-systems-on-site-services-gmbh/geoCore#48]
Hello,

We have another error trying to use the geoCore plugin.
We tried to adapt the config.yml file according to the youtube video and the manual.
Please find attached 3 files : the layer, the layer data and the config.yml, and below the TypeError.
Greetings

`Une erreur est survenue lors de l'éxécution du code Python: 

TypeError: reduce() of empty sequence with no initial value 
Traceback (most recent call last):
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 157, in showEvent
    self.drawProfilesNorthSouth()
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 277, in drawProfilesNorthSouth
    self._drawProfiles(crit)
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 306, in _drawProfiles
    painter.paint(pac, len(pac) == 1)
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profilePainter.py", line 68, in paint
    i.paint(self.scene)
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profile.py", line 55, in paint
    self._paintLegend(scene)
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profile.py", line 62, in _paintLegend
    yBottom = self.y - self.height()
  File "/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profile.py", line 40, in height
    return reduce(lambda x, y: x + y, [b.height for b in self.boxes])
TypeError: reduce() of empty sequence with no initial value

Version de Python : 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
Version de QGIS : 3.22.7-Białowieża Białowieża, 5a65627acb 

Chemin Python :
/usr/share/qgis/python
/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python
/home/vin
cent/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/vincent/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/vincent/.local/share/QGIS/QGIS3/profiles/default/python
.
/media/u_ppige09lambert93/LIDAR/Scarpe/20190228_RGEALTI_MNT_1M_ASC_LAMB93_IGN69_DGPR-17LI065-AUTHIE-BOULONNAIS/2022_ScarpeAmont_SIG_LIDAR
[files.zip](https://github.com/t-systems-on-site-services-gmbh/geoCore/files/8877964/files.zip)
`

**Comment by gricklom** [comment]
@MoritzMennenga Could you please take a look?

**Comment by MoritzMennenga** [comment]
Hey, 
same problem as before.
- As you can see in the pictures, the columnnames have to fit with the config.yml.
- You need x,y and z coorindates (you can add the coordinates with the Field Calculator -> $x ...)
- You need a name
As you can see, it works for me (without a adaption of the geoCore.yml not very good looking ;-) ). I attached the new files. 
- when you change the config.yml or geocore.yml you have to reload the plugin (easy via "Plugin Reloader") or restart Qgis
All the best

![main_data](https://user-images.githubusercontent.com/17044206/173048623-06441aba-dec4-4022-8581-6d3e269f0600.jpg)
![table_data](https://user-images.githubusercontent.com/17044206/173048633-013535aa-34e2-439c-9196-0ad9de0c7878.jpg)
![cores](https://user-images.githubusercontent.com/17044206/173049024-c1fe1378-7336-4ce8-8b9e-723b18b7f5a8.jpg)
[fehler.zip](https://github.com/t-systems-on-site-services-gmbh/geoCore/files/8878181/fehler.zip)

**Comment by PhilipMay** [comment]
@gricklom and @MoritzMennenga would it be possible to detect exceptions like this? After detection the program could ask the user if it should reload the plugin or restart Qgis.

Maybe that would be an upstream feature request?

**Comment by gricklom** [comment]
@MoritzMennenga Thanks for your support!
@PhilipMay We could probably add a sanity check to detect a mismatch between the configuration and the layer data and inform the user of such a mismatch.

**Comment by VincentD** [comment]
@gricklom, @MoritzMennenga and @PhilipMay Thank you very much! 
Really sorry for the noise, it was effectively again a problem of column name (in the data layer now).
Now I can see the profiles.
Thanks again for the plugin and the support!

**Comment by PhilipMay** [comment]
> Really sorry for the noise

I think I can speak for all of us when I say that we are always happy to get users and feedback. :-)
